question_data = [
        {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
         "question": "Who is Sonic&#039;s sidekick?", "correct_answer": "Tails",
         "incorrect_answers": ["Shadow", "Amy", "Knuckles"]},
        {"category": "History", "type": "multiple", "difficulty": "easy",
         "question": "Which of the following ancient peoples was NOT classified as Hellenic (Greek)?",
         "correct_answer": "Illyrians", "incorrect_answers": ["Dorians", "Achaeans", "Ionians"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "hard",
         "question": "In the anime, Full Metal Panic!, who is Kaname&#039;s best friend?",
         "correct_answer": "Kyoko Tokiwa",
         "incorrect_answers": ["Melissa Mao", "Ren Mikihara", "Teletha &quot;Tessa&quot; Testarossa"]},
        {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
         "question": "Which of these characters is the mascot of the video game company SEGA?",
         "correct_answer": "Sonic the Hedgehog", "incorrect_answers": ["Dynamite Headdy", "Alex Kidd", "Opa-Opa"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
         "question": "What character was once considered to be the 27th letter of the alphabet?",
         "correct_answer": "Ampersand", "incorrect_answers": ["Interrobang", "Tilde", "Pilcrow"]},
        {"category": "Entertainment: Books", "type": "multiple", "difficulty": "easy",
         "question": "What is the name of the three headed dog in Harry Potter and the Sorcerer&#039;s Stone?",
         "correct_answer": "Fluffy", "incorrect_answers": ["Spike", "Poofy", "Spot"]},
        {"category": "Mythology", "type": "multiple", "difficulty": "medium",
         "question": "According to the Egyptian Myth of Osiris, who murdered Osiris?", "correct_answer": "Set",
         "incorrect_answers": ["Horus", "Ra", "Anhur"]},
        {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
         "question": "Which of the following was not developed by Bethesda?", "correct_answer": "Fallout: New Vegas",
         "incorrect_answers": ["Fallout 3", "The Elder Scrolls V: Skyrim", "Fallout 4"]},
        {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
         "question": "What airline was the owner of the plane that crashed off the coast of Nova Scotia in 1998?",
         "correct_answer": "Swiss Air", "incorrect_answers": ["Air France", "British Airways", "TWA"]}
]
